### PR TITLE
feat: upgrade to api v2

### PR DESCRIPTION
**Pull request by caarlos0**
also fixed pagination issue with the old API version.

PS: I'm not fluent in python, let me know if my code sucks 😃

### CODE REVIEW

**Comment by caarlos0** [comment]
ping @bonovoxly

**Comment by bonovoxly** [comment]
@caarlos0 haven't tested it yet but cool - didn't even know coinmarketcap had a version 2 of the api.

**Comment by caarlos0** [comment]
yeah, v1 will stop working on November 30th :P

**Comment by caarlos0** [comment]
I did my best to keep the metrics with same names and etc...

**Comment by caarlos0** [comment]
thanks!

**Pull request merged**
